id = "1765918869-c1857090"
timestamp = "2025-12-16T21:01:09.994474944Z"
message = "Test"
dependencies = []

[table]
headers = [
    "ID",
    "Name",
    "Amount",
]
rows = [
    [
    "1",
    "Alice",
    "100",
],
    [
    "2",
    "Bob",
    "200",
],
]

[hashes]
table_hash = "c1857090b47d35c9329f0ce7a45f8a7e3d11a60037eb7096512706477d8749f0"
row_hashes = [
    "b0d8dee385fdcb69e76e731164e1bb6798be318a15c0a4364b37138f79a5aceb",
    "a6c9b9eb4a0b244d2b32a8667e9eba8f8018f1acc2c664f56ae7b97c6b534fa6",
]

[hashes.header_hashes]
ID = "fed013918fba1b57604876f5c10bcd110ce32d1964ad7cab823ec5e89279547e"
Name = "29430df008c2de7b511b86bbad229339704d6c21df3bd5b5b8b8170d4d339d45"
Amount = "e25bcc42fcaa0d7779ce440b24c1507758bdd592cf4c36b91568f25cd80353bc"
